### ISSUE TITLE
eza --extended  -l       together seem to case a segfault on macOS (Arm)

### ISSUE THREAD

**Issue by unixwizard107** [eza-community/eza#603] opened 2023-11-03 15:17 UTC
### Discussed in https://github.com/orgs/eza-community/discussions/602

<div type='discussions-op-text'>

<sup>Originally posted by **unixwizard107** November  3, 2023</sup>
Not sure how to report a bug, but I  thought you good  folks might like to know, I switched from esa to eza, but sadly  ran into a small hiccup this am on my mac (this used to work with the old program):

eza --extented works, as  does eza -l but together, bad things are occurring 

% eza -l --extended
zsh: segmentation fault  eza -l --extended

% which eza
/opt/homebrew/bin/eza

% eza --version
eza - A modern, maintained replacement for ls
v0.15.2 [+git]
https://github.com/eza-community/eza

% uname -a
Darwin xorn.ccc.com 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64 arm Darwin</div>

**Comment by cafkafk** [comment] 2023-11-03 17:36
Thanks for the report

**Comment by holmesrichards** [comment] 2023-11-03 21:59
Looks like a duplicate of https://github.com/eza-community/eza/issues/425

**Comment by cafkafk** [comment] 2023-11-04 10:46
Closed as duplicate of https://github.com/eza-community/eza/issues/425

**Closed by cafkafk** 2023-11-04 10:46 UTC
