### ISSUE TITLE
feat:  Omit group when it has the same value as the user

### ISSUE THREAD

**Issue by liketurbo** [eza-community/eza#379] opened 2023-09-18 20:30 UTC
`eza -lg` outputs a list of files, where often the user and group have the same value:
```
drwxr-xr-x    - test0 test0 25 Jul 19:19 folder0
drwxr-xr-x    - test0 test0 25 Jul 19:19 folder1
.rw-r--r--  135 test0 test1 18 Sep 18:28 file0
```

To improve readability, maybe, we only need to show the group when it differs from the user:
```
drwxr-xr-x    - test0     - 25 Jul 19:19 folder0
drwxr-xr-x    - test0     - 25 Jul 19:19 folder1
.rw-r--r--  135 test0 test1 18 Sep 18:28 file0
```

**Comment by cafkafk** [comment] 2023-09-19 03:01
> To improve readability, maybe, we only need to show the group when it differs from the user:

We've discussed adding `auto, always, never` to some flags, one of them could be user implicitly taking `auto`, meaning this behavior.

**Comment by cafkafk** [comment] 2023-10-05 09:08
Duplicate of #480.

**Closed by cafkafk** 2023-10-05 09:08 UTC
