### ISSUE TITLE
bug: Misalignment with icons enabled and spaces in file name

### ISSUE THREAD

**Issue by henryhchchc** [eza-community/eza#550] opened 2023-10-20 12:57 UTC
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`)
- The command-line arguments you are using
- Your operating system and hardware platform

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---
Version:

```
eza - A modern, maintained replacement for ls
v0.15.0 [+git]
https://github.com/eza-community/eza
```

Arguments: `eza --icons`

The items with spaces in their names takes two more spaces and results in misalignment for the items on the right.

<img width="1068" alt="image" src="https://github.com/eza-community/eza/assets/5498199/b7e1b993-984c-4ea5-a298-a7fbce5f8513">

**Comment by PThorpe92** [comment] 2023-10-20 13:11
closing as Duplicate of #547 

Should be fixed by #548

**Closed by PThorpe92** 2023-10-20 13:11 UTC
Labels: errors
