### ISSUE TITLE
bug: 0.18.18 release is missing executables

### ISSUE THREAD

**Issue by koterpillar** [eza-community/eza#1029] opened 2024-06-19 03:57 UTC
The ["Manual" section in INSTALL.md](https://github.com/eza-community/eza/blob/main/INSTALL.md#manual-linux) instructs to download a file such as `eza_x86_64-unknown-linux-gnu.tar.gz` from the latest release, but at the time of writing, [v0.18.18](https://github.com/eza-community/eza/releases/tag/v0.18.18) doesn't have any artifacts uploaded but `{completions,man}-0.18.18.tar.gz`.

**Comment by cafkafk** [comment] 2024-06-19 05:26
duplicate of https://github.com/eza-community/eza/issues/1023, should be solved tomorrow

**Closed by cafkafk** 2024-06-19 05:26 UTC
Labels: errors
