### ISSUE TITLE
bug: Windows globbing in cmd and PS

### ISSUE THREAD

**Issue by vbd** [eza-community/eza#493] opened 2023-10-07 10:45 UTC
- eza 0.14.0
- Windows 11
- tested with cmd
- tested with Powershell (PSVersion 5.1.22621.1778, can't currently update to PS >= 6)
- probably issues #337, #404 related

Just downloaded eza and played with it.
Looks impressing and is a lot faster compared to [lsd] which I used up to now.

 
1. OK -- listing only file shortcuts.ahk
~~~
    eza -lB -snew --time-style long-iso --group-directories-first shortcuts.ahk
    ...
    -a--- 12,331 2023-10-07 12:04 shortcuts.ahk
 ~~~

2. OK -- listing all files matching shortcuts* by chaining with rg

~~~
    eza -lB -snew --time-style long-iso --group-directories-first | rg shortcuts*
    -a---        323 2012-10-06 09:32 shortcuts.md
    -a---      1,111 2012-10-06 09:32 shortcuts.html
    -a---     10,256 2023-09-10 10:58 shortcuts.ods
    -a---     12,331 2023-10-07 12:04 shortcuts.ahk
~~~

3. NOK -- trying the same as in 2 without chaining rg

~~~
    eza -lB -snew --time-style long-iso --group-directories-first shortcuts*
    ...
    "shortcuts*": Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch. (os error 123)
~~~

Shouldn't this work, too? Did I do something wrong?

[lsd]: https://github.com/lsd-rs/lsd

**Comment by MartinFillon** [comment] 2023-10-07 13:33
As you self-mentionned this is indeed a duplicate of #337 and is so because of powershell gestion of globbings that is different from lunix's shells

**Comment by cafkafk** [comment] 2023-10-08 03:43
Closing as duplicate of https://github.com/eza-community/eza/issues/337 for now

**Closed by cafkafk** 2023-10-08 03:43 UTC
Labels: errors
