### ISSUE TITLE
bug: using `--icons --classify` flag breaks grid output

### ISSUE THREAD

**Issue by OmeletWithoutEgg** [eza-community/eza#578] opened 2023-10-29 03:29 UTC
When using following arguments, the grid output seems a little broken.

```
eza --icons -F
```

![image](https://github.com/eza-community/eza/assets/50587059/fb6fe49d-283d-4f07-9727-b19ff7159179)

Only using both `--icons` and `--classify` will result in wrong output.

The version is
```
eza - A modern, maintained replacement for ls
v0.15.1 [+git]
https://github.com/eza-community/eza
```

The OS is archlinux, and I'm using KDE plasma with wezterm terminal emulator.

**Comment by cafkafk** [comment] 2023-10-29 06:02
Wonder if this is related to #267

**Comment by ankitson** [comment] 2023-11-24 00:03
I have a fix for this:
```
[23/11/23 15:57]ankit@devbox:~/code/external-repo/eza (fix-grid-classify-bug *)$ g d
diff --git a/src/output/grid.rs b/src/output/grid.rs
index 5293348c..f51177a4 100644
--- a/src/output/grid.rs
+++ b/src/output/grid.rs
@@ -91,7 +91,11 @@ impl<'a> Render<'a> {
                 contents: contents.strings().to_string(),
                 // with hyperlink escape sequences,
                 // the actual *contents.width() is larger than actually needed, so we take only the filename
-                width,
+                width: width + classification_width,
```

but I have no idea why it works...

I just see that the grid breaks in this way - when both `classify` and `icons` are used together, there is an extra space after files with a trailing `/` (or other symbol) from the `classify`. So this adjusts the width to account for that.  So I won't submit this as a PR unless/until I figure out why it works but it may be useful to modify your own fork. If anyone can explain what's happening, that would be nice too :)

**Comment by PThorpe92** [comment] 2023-11-24 00:20
Oh that is weird.. I thought this was fixed already. Yeah that should work as a temporary solution. I have (slowly) been working on a more permanent solution but that has been hitting speedbumps lately :/

**Comment by ankitson** [comment] 2023-11-24 00:35
> Oh that is weird.. I thought this was fixed already. Yeah that should work as a temporary solution. I have (slowly) been working on a more permanent solution but that has been hitting speedbumps lately :/

Hmm okay. if you're looking for help, is there any info/docs on why it happens or the solution you're working on?

**Comment by PThorpe92** [comment] 2023-11-24 12:40
The reason it happens is because calculations of width currently are kinda hacky and hyperlinks (the inability to properly escape the ansi escape codes needed, in combination with finding the width of the grapheme clusters) cause us to use the naive calculation of the width instead of the function (`*contents.width()`) to get the unicode width, otherwise it will be wider than we need.
This is just an ongoing problem, the solution is I need to migrate us over to a different library that handles hyperlinks internally so we don't have to do width calculations ourselves, allowing us to be able to then migrate over to a new version of another library, which will then handle all other calculations. (convenient)

That is all stuff I'm going to have to do myself but you are welcome to put in a PR with a fix for specifically the classification issue :+1: .
The classification width needs to get added to 
```rust
                    ShowIcons::Always(spacing) | ShowIcons::Automatic(spacing),
                ) => {
                    filename.bare_width()
                        + 1
                        + (spacing as usize)
                        + space_filename_offset
                        + classification_width // <- here
                }
                (EmbedHyperlinks::Off, _) => *contents.width(),
            };

            grid.add(tg::Cell {
                contents: contents.strings().to_string(),
                // with hyperlink escape sequences,
                // the actual *contents.width() is larger than actually needed, so we take only the filename
                width, // <- where i think u added it 
            });
        }

**Closed** 2023-11-25 23:28 UTC
Labels: errors

**Comment by chrisant996** [comment] 2024-02-06 20:05
Is this expected to be fixed in v0.18.0 released Jan 31, 2024?
It's not working:

**Problem:**

`eza -F --icons` results in incorrect grid alignment.
Each `/` shifts the rest of the row by 1 character.

(I just found eza, and this was the first command I tried.)

**Screen shot:**

![image](https://github.com/eza-community/eza/assets/17440311/5c4f8224-1be3-4526-bcf7-d582dc826c37)

Info | Details
-|-
Version: | v0.18.0 [+git]
Command: | `eza -F --icons`
OS: | Windows 10 Pro 22H2 19045.3930
Hardware: | 64 bit, Intel i7-10870H processor, 32 GB RAM

**Comment by mathomp4** [comment] 2024-02-06 20:21
I can confirm I still see this as well.

**Comment by MartinFillon** [comment] 2024-02-07 08:38
Strange gonna look at this
