### ISSUE TITLE
bug: displaced items when displaying icons

### ISSUE THREAD

**Issue by fnuttens** [eza-community/eza#556] opened 2023-10-22 20:22 UTC
I noticed some kind of alignment issue when displaying a grid of items along with their icons:

![eza-icons-alignment](https://github.com/eza-community/eza/assets/8812165/d5d801f4-a6bb-41e1-8452-772222bcbd2e)

Extra information:
- eza version: `0.15.0`
- command-line arguments: `eza --icons=(auto|always)`
- OS: Windows 10

**Comment by PThorpe92** [comment] 2023-10-22 20:30
Thanks for the bug report. Thankfully this should be fixed by #551 and but is a duplicate of #547 and #543 so I'll close in favor of exisitng :+1:

**Closed by PThorpe92** 2023-10-22 20:30 UTC
Labels: errors

**Comment by donovanglover** [comment] 2023-10-31 21:20
Running NixOS with eza 0.15.1 and this is still an issue with CJK text

**Comment by donovanglover** [comment] 2023-10-31 21:46
Looks like the issue started somewhere between [0.14.2 and 0.15.0](https://github.com/eza-community/eza/compare/v0.14.2...v0.15.0). Anyone interested in doing a git bisect?
