### ISSUE TITLE
feat:  Include compiled man pages in the linux release assets

### ISSUE THREAD

**Issue by j-xella** [eza-community/eza#695] opened 2023-11-30 10:41 UTC
Would it be possible to include proper man pages in linux assets of each release?

There are only markdown pages ATM. It is possible to convert them to man pages, but it requires installing additional software like pandoc etc... , which may not always be easy, and adds time and efforts when deploying new versions of `eza`.

Some things I noticed when manually converting md pages to man pages (note: I used [online pandoc converter](https://pandoc.org/try/) for that):

* They need to be put in appropriate folders (ex `share/man/man1`)
* They contain `$version` token that needs to be replaces with a proper eza version
* They contain links to each other, which look like `page_name.5.md`. In man page, such links would look better as `page_name(5)`

**Comment by cafkafk** [comment] 2023-11-30 11:29
Duplicate of #357, but yes this is planned

**Closed by cafkafk** 2023-11-30 11:29 UTC
