### ISSUE TITLE
User and Group always show ID instead of name

### ISSUE THREAD

**Issue by anhnt-2136** [eza-community/eza#616] opened 2023-11-06 04:20 UTC
```
OS: Ubuntu 20.04.6 LTS
Version: v0.15.1
```
Hi guys.

I'm using `eza -algho` but the result always shows User and Group ID, I can't find any command option to show the name instead. `exa` still shows the name
![Screenshot from 2023-11-06 11-20-02](https://github.com/eza-community/eza/assets/60587803/9dd817ef-fcfb-4b15-93f5-fd30a0a4e628)

**Comment by MartinFillon** [comment] 2023-11-06 08:44
Cannot reproduce under Ubuntu 23.04 with eza version: v0.15.1 [+git]

**Comment by MartinFillon** [comment] 2023-11-06 08:45
How did you install eza ? Cargo ? apt ?

**Comment by gierens** [comment] 2023-11-06 09:08
I cannot reproduce this either on a Ubuntu 20.04.3 LTS and eza v0.15.1 installed via apt.

**Comment by anhnt-2136** [comment] 2023-11-06 09:19
@MartinFillon I installed via apt. Lemme try install it again
@gierens that weird

**Comment by gierens** [comment] 2023-11-06 09:19
I updated the deb repo to v0.15.2 just now, if you installed it via apt then maybe try that version.

**Comment by anhnt-2136** [comment] 2023-11-06 09:22
@gierens I updated the deb repo to v.015.2 but it still show the ID

**Comment by gierens** [comment] 2023-11-06 09:23
can you send us the output of `id`?

**Comment by anhnt-2136** [comment] 2023-11-06 09:26
@gierens Same as my first comment, the `User` and `Group` columns show the ID of my user instead of the name

**Comment by gierens** [comment] 2023-11-06 09:29
No I mean the shell command `id`. I wanna see the output of that.

On my ubuntu 20 test machine it looks like this for example:
![Screenshot from 2023-11-06 10-28-45](https://github.com/eza-community/eza/assets/49617392/31bfeaf7-9074-413d-a6f5-4979b9433350)

**Comment by anhnt-2136** [comment] 2023-11-06 09:31
Oh ok, I'm misunderstood. Here is the result
```
uid=1208605825(xxx) gid=1208600513(domain users@xxx) groups=1208600513(domain users@xxx),4(adm),27(sudo),998(docker),1208600571(allowed rodc password replication group@xxx),1208606753(vpn_office@xxx)
```

**Comment by anhnt-2136** [comment] 2023-11-06 09:34
@gierens I tried in the virtual machine and It shows the user name that I expected

**Comment by gierens** [comment] 2023-11-06 09:37
> ```
> uid=1208605825(xxx) gid=1208600513(domain users@xxx) groups=1208600513(domain users@xxx),4(adm),27(sudo),998(docker),1208600571(allowed rodc password replication group@xxx),1208606753(vpn_office@xxx)
> ```

Is this a company machine? Or are you using PAM for user management or anything?

**Comment by anhnt-2136** [comment] 2023-11-06 09:38
Yes, this is a company machine. I tried at my colleague computer and it's working too

**Comment by gierens** [comment] 2023-11-06 09:46
Ok, interesting. But his `id` shows similar things? Like `gid=1208600513(domain users@xxx)`?

Hm, my guess would be that we have some problem with PAM here ... to investigate this we will first have to reproduce it ... so setup a test machine with PAM and stuff, that could take a while though.

We'll look into it! Thanks for reporting this!

**Comment by anhnt-2136** [comment] 2023-11-06 09:46
@gierens I just noticed that it shows the ID with files/folders that are owned by my user/group, other user/groups like root, docker... still show the name
![Screenshot from 2023-11-06 16-45-31](https://github.com/eza-community/eza/assets/60587803/b3e77d48-9c38-43b6-8ed2-74ed93a68971)
![Screenshot from 2023-11-06 16-45-46](https://github.com/eza-community/eza/assets/60587803/044c5f02-236a-4c2e-9d0d-0200073d20db)

**Comment by gierens** [comment] 2023-11-06 09:47
Yep, that's what I would expect because root, docker and stuff are managed locally and not by PAM.

**Comment by anhnt-2136** [comment] 2023-11-06 09:51
Yes, the name path inside round brackets is the same, only  the ID is different

**Comment by gierens** [comment] 2023-11-06 09:54
Hm, ok that's interesting ... then this could also be that something with you PAM setup in particular is wrong.

Anyway, we are going to try to reproduce this!

**Comment by anhnt-2136** [comment] 2023-11-06 10:00
@gierens Thanks. Let me know if I can help in any way.

**Comment by cfxegbert** [comment] 2023-11-06 10:08
What is your configuration for passwd and groups in /etc/nsswitch.conf?

**Comment by anhnt-2136** [comment] 2023-11-06 10:14
@cfxegbert here
```
passwd:         files systemd sss
group:          files systemd sss
```

**Comment by cfxegbert** [comment] 2023-11-06 10:32
As a test can you try switching the order on passwd, group, and shadow, to
```
passwd:         files sss systemd
group:          files sss systemd
shadow:         files sss systemd
```

**Comment by simaoafonso-pwt** [comment] 2023-12-01 11:55
I have the same issue on CentOS 7, using [x64 musl version of eza 0.16.1](https://github.com/eza-community/eza/releases/download/v0.16.1/eza_x86_64-unknown-linux-musl.tar.gz).

PAM is working correctly:

```
$ eza -lg
drwxr-xr-x    - 10914 LGROUP    1 Dec 11:45 FOLDER
$ getent passwd $USER
$USER:*:10914:10013::/home/$USER:/bin/tcsh
```

**Comment by simaoafonso-pwt** [comment] 2023-12-01 11:58
I can't use the GNU version on CentOS 7, it was built on a too new glibc:

```
$ eza -lg
eza: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by eza)
$ /lib64/libc.so.6
GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.5 20150623 (Red Hat 4.8.5-44).
Compiled on a Linux 3.10.0 system on 2022-05-18.
Available extensions:
	The C stubs add-on version 2.1.2.
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	Native POSIX Threads Library by Ulrich Drepper et al
	BIND-8.2.3-T5B
	RT using linux kernel aio
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```

**Comment by BobobUnicorn** [comment] 2024-02-01 21:44
I encountered this issue; in my case, it seems to be due to the way `nsswitch.conf` is configured (requires `nss_cache`) and the nix-store installed version bringing in its own `libc.so`; the quick fix here was to prepend `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libnss_cache.so.2`. I'm not entirely sure what the most reasonable solution for that is.

**Comment by apoorvkh** [comment] 2024-02-24 07:15
I also had this problem and switching from `eza_x86_64-unknown-linux-musl` to `eza_x86_64-unknown-linux-gnu` fixed it for me.

**Comment by gierens** [comment] 2024-03-21 13:23
This appears to be a duplicate of #541 therefore I'm going to close this one. We'll continue the discussion there.

**Closed by gierens** 2024-03-21 13:23 UTC
Labels: errors, duplicate, question, errors › invalid output, output
