### ISSUE TITLE
ci: doesn't build on mac (M2) OS 13.5.2 (22G91)

### ISSUE THREAD

**Issue by dominix** [eza-community/eza#353] opened 2023-09-15 18:07 UTC
If eza fails to compile, or if there is a problem during the build process, then please include the following information in your report:

- The exact eza commit you are building (`git rev-parse --short HEAD`)
this is for eza V0.12.0

- The version of rustc you are compiling it with (`rustc --version`)
rustc 1.72.0 (5680fa18f 2023-08-23) (Homebrew)

- Your operating system and hardware platform
MacOS Ventura 13.5.2

- The Rust build target (the _exact_ output of `rustc --print cfg`)
rustc --print cfg
debug_assertions
panic="unwind"
target_arch="aarch64"
target_endian="little"
target_env=""
target_family="unix"
target_feature="aes"
target_feature="crc"
target_feature="dit"
target_feature="dotprod"
target_feature="dpb"
target_feature="dpb2"
target_feature="fcma"
target_feature="fhm"
target_feature="flagm"
target_feature="fp16"
target_feature="frintts"
target_feature="jsconv"
target_feature="lor"
target_feature="lse"
target_feature="neon"
target_feature="paca"
target_feature="pacg"
target_feature="pan"
target_feature="pmuv3"
target_feature="ras"
target_feature="rcpc"
target_feature="rcpc2"
target_feature="rdm"
target_feature="sb"
target_feature="sha2"
target_feature="sha3"
target_feature="ssbs"
target_feature="vh"
target_has_atomic="128"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="macos"
target_pointer_width="64"
target_vendor="apple"
unix

If you are seeing compilation errors, please include the output of the build process.

$ cargo install eza
    Updating crates.io index
  Downloaded eza v0.12.0
  Downloaded 1 crate (157.8 KB) in 0.66s
  Installing eza v0.12.0
    Updating crates.io index
  Downloaded urlencoding v2.1.3
  Downloaded terminal_size v0.2.6
  Downloaded phf_generator v0.11.2
  Downloaded timeago v0.4.1
  Downloaded phf_macros v0.11.2
  Downloaded iana-time-zone v0.1.57
  Downloaded phf_shared v0.11.2
  Downloaded phf v0.11.2
  Downloaded unicode-ident v1.0.12
  Downloaded ansiterm v0.12.2
  Downloaded proc-macro2 v1.0.67
  Downloaded uzers v0.11.3
  Downloaded chrono v0.4.31
  Downloaded git2 v0.18.0
  Downloaded libc v0.2.148
  Downloaded syn v2.0.33
  Downloaded libgit2-sys v0.16.1+1.7.1
  Downloaded 17 crates (3.4 MB) in 2.39s (largest was `libgit2-sys` at 1.8 MB)
   Compiling libc v0.2.148
   Compiling autocfg v1.1.0
   Compiling pkg-config v0.3.27
   Compiling proc-macro2 v1.0.67
   Compiling vcpkg v0.2.15
   Compiling tinyvec_macros v0.1.1
   Compiling unicode-ident v1.0.12
   Compiling tinyvec v1.6.0
   Compiling core-foundation-sys v0.8.4
   Compiling io-lifetimes v1.0.11
   Compiling num-traits v0.2.16
   Compiling rand_core v0.6.4
   Compiling siphasher v0.3.11
   Compiling phf_shared v0.11.2
   Compiling rand v0.8.5
   Compiling iana-time-zone v0.1.57
   Compiling unicode-bidi v0.3.13
   Compiling unicode-normalization v0.1.22
error: failed to run custom build command for `io-lifetimes v1.0.11`

Caused by:
  process didn't exit successfully: `/var/folders/99/vbry9j7x52s4h7s7rkhtynx40000gn/T/cargo-install7cm65A/release/build/io-lifetimes-50ec94488e424dd3/build-script-build` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `num-traits v0.2.16`

Caused by:
  process didn't exit successfully: `/var/folders/99/vbry9j7x52s4h7s7rkhtynx40000gn/T/cargo-install7cm65A/release/build/num-traits-7d48df6d64c76b30/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to run custom build command for `proc-macro2 v1.0.67`

Caused by:
  process didn't exit successfully: `/var/folders/99/vbry9j7x52s4h7s7rkhtynx40000gn/T/cargo-install7cm65A/release/build/proc-macro2-9a6b62c055bacc34/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to run custom build command for `libc v0.2.148`

Caused by:
  process didn't exit successfully: `/var/folders/99/vbry9j7x52s4h7s7rkhtynx40000gn/T/cargo-install7cm65A/release/build/libc-c927c5145b186010/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to run custom build command for `libc v0.2.148`

Caused by:
  process didn't exit successfully: `/var/folders/99/vbry9j7x52s4h7s7rkhtynx40000gn/T/cargo-install7cm65A/release/build/libc-fded663cd0eded68/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to compile `eza v0.12.0`, intermediate artifacts can be found at `/var/folders/99/vbry9j7x52s4h7s7rkhtynx40000gn/T/cargo-install7cm65A`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
---

**Comment by vladdoster** [comment] 2023-09-23 01:43
This is a PATH issue, and not an issue with rust.

I had the same issue, but ran across this [rust-lang/cargo issue](https://github.com/rust-lang/cargo/issues/11641). 

<img width="1006" alt="Screenshot 2023-09-22 at 8 35 11 PM" src="https://github.com/eza-community/eza/assets/10052309/5618034b-6a82-43c1-be88-96c5ba34c7c0">

I was able to compile after starting a new shell process.

<img width="707" alt="Screenshot 2023-09-22 at 8 35 17 PM" src="https://github.com/eza-community/eza/assets/10052309/6651af69-3eb2-4803-9deb-6b8c68c8ffa0">


<img width="982" alt="Screenshot 2023-09-22 at 8 41 23 PM" src="https://github.com/eza-community/eza/assets/10052309/69d992b9-9411-49e8-a383-46cfff4c9f7f">

**Comment by MartinFillon** [comment] 2023-09-28 11:55
@dominix is your issue still on going or this the comment from @vladdoster helped ?

**Comment by dominix** [comment] 2023-09-28 12:18
sorry, but no still didn't compile successfully

 cargo install eza
    Updating crates.io index
  Installing eza v0.13.1
    Updating crates.io index
   Compiling libc v0.2.148
   Compiling autocfg v1.1.0
   Compiling pkg-config v0.3.27
   Compiling proc-macro2 v1.0.67
   Compiling vcpkg v0.2.15
   Compiling tinyvec_macros v0.1.1
   Compiling unicode-ident v1.0.12
   Compiling tinyvec v1.6.0
   Compiling rand_core v0.6.4
   Compiling siphasher v0.3.11
   Compiling num-traits v0.2.16
error: failed to run custom build command for `libc v0.2.148`

Caused by:
  process didn't exit successfully: `/var/folders/99/vbry9j7x52s4h7s7rkhtynx40000gn/T/cargo-installvEf2VN/release/build/libc-4822fd2892371840/build-script-build` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `proc-macro2 v1.0.67`

Caused by:
  process didn't exit successfully: `/var/folders/99/vbry9j7x52s4h7s7rkhtynx40000gn/T/cargo-installvEf2VN/release/build/proc-macro2-3ce084957f894fa8/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to compile `eza v0.13.1`, intermediate artifacts can be found at `/var/folders/99/vbry9j7x52s4h7s7rkhtynx40000gn/T/cargo-installvEf2VN`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by dominix** [comment] 2023-09-28 12:24
same with clone  github repo and run locally with --path

eza $ cargo install --path .
  Installing eza v0.13.1 (/Users/dominix/src/GIT/eza)
    Updating crates.io index

   Compiling libc v0.2.148
   Compiling autocfg v1.1.0
   Compiling pkg-config v0.3.27
   Compiling vcpkg v0.2.15
   Compiling proc-macro2 v1.0.67
   Compiling unicode-ident v1.0.12
   Compiling tinyvec_macros v0.1.1
   Compiling tinyvec v1.6.0
   Compiling siphasher v0.3.11
   Compiling core-foundation-sys v0.8.4
   Compiling num-traits v0.2.16
   Compiling rand_core v0.6.4
   Compiling rand v0.8.5
   Compiling iana-time-zone v0.1.57
   Compiling phf_shared v0.11.2
error: failed to run custom build command for `libc v0.2.148`

Caused by:
  process didn't exit successfully: `/Users/dominix/src/GIT/eza/target/release/build/libc-4822fd2892371840/build-script-build` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `libc v0.2.148`

Caused by:
  process didn't exit successfully: `/Users/dominix/src/GIT/eza/target/release/build/libc-7e3149ba74e9e746/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to run custom build command for `proc-macro2 v1.0.67`

Caused by:
  process didn't exit successfully: `/Users/dominix/src/GIT/eza/target/release/build/proc-macro2-3ce084957f894fa8/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to run custom build command for `num-traits v0.2.16`

Caused by:
  process didn't exit successfully: `/Users/dominix/src/GIT/eza/target/release/build/num-traits-e2fbd66603389cea/build-script-build` (signal: 9, SIGKILL: kill)
error: failed to compile `eza v0.13.1 (/Users/dominix/src/GIT/eza)`, intermediate artifacts can be found at `/Users/dominix/src/GIT/eza/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by MartinFillon** [comment] 2023-09-28 12:35
Could you try to `cargo build` locally because this looks like a common error from rust programs on MacOS so it might not be an eza error.

**Comment by dominix** [comment] 2023-09-28 12:40
cargo build : build fine

:eza $ cargo build
   Compiling libc v0.2.148
   Compiling pkg-config v0.3.19
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.66
   Compiling tinyvec_macros v0.1.0
   Compiling unicode-ident v1.0.11
   Compiling matches v0.1.8
   Compiling siphasher v0.3.11
   Compiling tinyvec v1.2.0
   Compiling core-foundation-sys v0.8.4
   Compiling rand_core v0.6.4
   Compiling iana-time-zone v0.1.57
   Compiling num-traits v0.2.14
   Compiling rand v0.8.5
   Compiling phf_shared v0.11.2
   Compiling unicode-bidi v0.3.5
   Compiling percent-encoding v2.3.0
   Compiling bitflags v2.4.0
   Compiling rustix v0.38.13
   Compiling phf_generator v0.11.2
   Compiling form_urlencoded v1.0.1
   Compiling log v0.4.20
   Compiling unicode-width v0.1.11
   Compiling unicode-normalization v0.1.17
   Compiling byteorder v1.4.3
   Compiling term_grid v0.1.7
   Compiling natord v1.0.9
   Compiling glob v0.3.1
   Compiling timeago v0.4.2
   Compiling scoped_threadpool v0.1.9
   Compiling idna v0.2.3
   Compiling number_prefix v0.4.0
   Compiling chrono v0.4.31
   Compiling lazy_static v1.4.0
   Compiling ansiterm v0.12.2
   Compiling jobserver v0.1.22
   Compiling cc v1.0.79
   Compiling quote v1.0.33
   Compiling url v2.2.1
   Compiling syn v2.0.29
   Compiling libz-sys v1.1.2
   Compiling libgit2-sys v0.16.1+1.7.1
   Compiling errno v0.3.3
   Compiling datetime v0.5.2
   Compiling num_cpus v1.16.0
   Compiling uzers v0.11.3
   Compiling locale v0.2.2
   Compiling eza v0.13.1 (/Users/dominix/src/GIT/eza)
   Compiling zoneinfo_compiled v0.5.1
   Compiling terminal_size v0.3.0
   Compiling phf_macros v0.11.2
   Compiling phf v0.11.2
   Compiling git2 v0.18.1
    Finished dev [unoptimized] target(s) in 7.95s

**Comment by MartinFillon** [comment] 2023-09-28 12:42
Okay that is clearly not an eza issue. You should try to have a look on internet as the issue is known for other packages.

**Comment by dominix** [comment] 2023-09-28 12:43
ok, is a cargo only  issue ?

**Comment by MartinFillon** [comment] 2023-09-28 12:45
Looks like it

**Comment by MartinFillon** [comment] 2023-09-28 12:46
You should look into what does custom build script needs maybe you miss some apps ?

**Comment by vladdoster** [comment] 2023-09-30 10:50
It still looks like a `$PATH` issue as the error is identical to the one I encountered. 

---

In the eza repository directory, run:

```zsh
# Start a fresh zsh process 
# -c clears env variables && --norcs skips loading zsh configuration files
exec -c zsh --no-rcs --no-global-rcs
# Configure your shell (assuming it is $HOME/.cargo)
source "$HOME/.cargo/env"
cargo clean
cargo install --path .
```

**Comment by MartinFillon** [comment] 2023-09-30 23:13
I dont know what the issue is buut this is clearly not an eza issue, I am closing this

**Closed by MartinFillon** 2023-09-30 23:13 UTC
Labels: os › macos, errors › build error

**Comment by dominix** [comment] 2023-11-02 14:23
@vladdoster was right, it was related to a PATH. the command strip from MacoS conflict with the one installed by brew from package binutils. that recommended 
PATH="/opt/homebrew/opt/binutils/bin:$PATH"
So in my .bash-profile I have changed PATH to be 
PATH="$PATH:/opt/homebrew/opt/binutils/bin"
and now cargo stuff compile correctly eza, and other things as well.

**Comment by dominix** [comment] 2023-11-02 14:24
sorry for the noise. Hope it helps someone else if it happen to have the same problem.
