### ISSUE TITLE
bug: spacing issues with hyperlink

### ISSUE THREAD

**Issue by Scartiloffista** [eza-community/eza#515] opened 2023-10-11 14:00 UTC
seems that the `--hyperlink` feature has some spacing issues
![Screenshot 2023-10-11 at 15 54 06](https://github.com/eza-community/eza/assets/36407154/92d9d7fb-5138-4244-b245-fc68c8ae8cc7)

**Comment by Equationzhao** [comment] 2023-10-11 14:47
looks like it's caused by the `'`.

**Comment by cafkafk** [comment] 2023-10-11 16:13
Can confirm this

**Comment by MartinFillon** [comment] 2023-10-27 08:31
This looks like a mac issue there is a duplicate of this in #543

**Comment by holmesrichards** [comment] 2023-10-27 14:59
This is about hyperlinks not being displayed correctly, #543 is about hyperlinks not working.

**Comment by MartinFillon** [comment] 2023-10-27 15:02
Yeah I saw but I think that both are linked

**Comment by Scartiloffista** [comment] 2023-10-28 11:15
in 0.15.1 the bug seems fixed, at least for me

**Comment by cafkafk** [comment] 2023-10-29 06:03
Closing as solved then, if anyone else hits this on 0.15.1 or after we can reopen.

**Closed by cafkafk** 2023-10-29 06:03 UTC
Labels: errors
