### ISSUE TITLE
bug: Alignment issue with long cyrillic names

### ISSUE THREAD

**Issue by AlexKurisu** [eza-community/eza#566] opened 2023-10-26 06:12 UTC
`eza --version` : `v0.15.0 [+git]`. Running `eza --icons=auto --color=auto --group-directories-first`. OS: Archlinux on AMD64.

![image](https://github.com/eza-community/eza/assets/60626727/d7a4d3db-4879-4d3d-90cd-98fa6e092c14)

Used version of `eza` from commit bba97b5a835997e00f05971948a371149a17b403 that should have fixed this, but, sadly, it didn't

**Comment by cafkafk** [comment] 2023-10-26 07:31
Does it work for non-cyrillic names for you?

**Comment by AlexKurisu** [comment] 2023-10-26 07:43
> Does it work for non-cyrillic names for you? What terminal, font? Do you have ligatures enabled?

Alignment is fine for non-cyrillic names. Terminal is WezTerm, font is `IosevkaTerm Nerd Font`, ligatures are off.
Also, for some reason after renaming problematic directories grid was layouted differently

Alignment after rename (grapheme cluster length is the same):
![image](https://github.com/eza-community/eza/assets/60626727/1b2b6ef9-5b7d-41b1-b0aa-298ccdf84d9f)

Grid layout before rename:
![image](https://github.com/eza-community/eza/assets/60626727/6cfac3ab-338d-4dc5-9f03-60b4904e5162)

Grid layout after rename:
![image](https://github.com/eza-community/eza/assets/60626727/0bd1bd9d-8f52-484d-b329-cf7d2e2730b1)

**Comment by AlexKurisu** [comment] 2023-10-26 07:44
I suspect that eza or it's dependencies use string length in bytes instead of grapheme cluster length, but i have zero knowledge of Rust to confirm that

**Comment by cafkafk** [comment] 2023-10-26 07:49
> I suspect that eza or it's dependencies use string length in bytes instead of grapheme cluster length to calculate the alignment, but i have zero knowledge of Rust to confirm that

That sounds plausible, looking at the definition of length `.len()` of a `String` in the standard library:

> Returns the length of this String, in bytes, not [char](https://doc.rust-lang.org/std/primitive.char.html)s or graphemes. In other words, it might not be what a human considers the length of the string. [1]

[1]: https://doc.rust-lang.org/std/string/struct.String.html#method.len

**Comment by PThorpe92** [comment] 2023-10-26 12:39
interesting.. we stuck with our own (rustadopt) fork of ansiterm instead of moving to nu_ansi_term specifically because of the api change and how exa calculated the width of unicode variable width characters.
I'm curious to see where this regressed exactly

**Comment by AlexKurisu** [comment] 2023-10-26 15:00
> interesting.. we stuck with our own (rustadopt) fork of ansiterm instead of moving to nu_ansi_term specifically because of the api change and how exa calculated the width of unicode variable width characters. I'm curious to see where this regressed exactly

I'm going to try and build `exa`, maybe this is a bug since `exa` times

**Comment by AlexKurisu** [comment] 2023-10-26 15:04
This was not a thing in `exa`
![image](https://github.com/eza-community/eza/assets/60626727/49d8673c-4bf5-4506-a7bb-68c780d7b808)

**Comment by AlexKurisu** [comment] 2023-10-26 15:04
Also, the bug in `eza` is still there with `--no-quotes`

**Comment by PThorpe92** [comment] 2023-10-26 16:32
I believe I have found the problem.. 

At some point, `*contents.width()`, which is the exact function that made us fork `ansiterm-rs`, which calculates the actual width of a unicode string in terms of an `ANSI` string, for options where `icons`, `hyperlinks`, `quotes` are enabled,  was replaced with `filename.bare_width()` which is just the `string.len()`

There is this: 
```
// the actual *contents.width() is larger than actually needed, so we take only the filename
```

I'm currently testing moving back to the previous option. Hopefully there will be no other regressions caused by it

**Comment by AlexKurisu** [comment] 2023-10-26 17:16
@PThorpe92 I attempted to bisect the bad commit. Seems like it broke with commit 45857f0cf0526effcb6dd77f2af6376592323137

**Comment by AlexKurisu** [comment] 2023-10-26 17:21
@PThorpe92 Yep, it's the icons that somehow break alignment. Cannot reproduce on latest version with `--icons=never`

**Comment by PThorpe92** [comment] 2023-10-26 18:42
what the hell...

that certainly wasn't the commit I was expecting :eyes:  

Thanks for the tip that should make it much easier to solve

**Comment by hasecilu** [comment] 2023-11-02 01:01
Hi, it seems there is problem with other characteras as fractions:
![image](https://github.com/eza-community/eza/assets/53124818/f7d981f6-3988-43b0-a996-931a58117c35)

the problem seems to be with `--icons`
![image](https://github.com/eza-community/eza/assets/53124818/d88405d6-40e1-4983-b70c-58120a6e2faa)

**Comment by PThorpe92** [comment] 2023-11-02 01:05
>the problem seems to be with --icons

yeah that's what was discovered..

>Yep, it's the icons that somehow break alignment. Cannot reproduce on latest version with --icons=never

**Closed** 2023-12-25 21:23 UTC
Labels: errors

**Comment by cafkafk** [comment] 2024-01-03 09:46
:tada:

**Comment by Kamek437** [comment] 2024-06-20 04:20
Looks like this one cropped back up somehow.
