### ISSUE TITLE
bug: Grid incorrectly aligned when directories are present

### ISSUE THREAD

**Issue by pallaswept** [eza-community/eza#848] opened 2024-02-17 20:19 UTC
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`) v0.18.2 [+git]
- The command-line arguments you are using: 
`eza --colour=auto --colour-scale=all --color-scale-mode=gradient --icons=auto --hyperlink --long --classify=auto --all --all --group-directories-first --sort=type --sort=extension --sort=modified --sort=name --binary --smart-group --header --modified  --extended --octal-permissions --git --git-repos --time-style='+%d %b %Y %H:%M
%d %b %Y %H:%M:%S -G`
actually aliased without the -G to `ls` so in the below examples you see me just do `ls -G`, but it amounts to the above.
- Your operating system and hardware platform: OpenSUSE Tumbleweed KDE Plasma  Wayland AMD Zen3 CPU Nvidia 30 series GPU (proprietary driver) (can be more specific if req'd, but I feel like it won't be relevant)

---

The output of the grid is misaligned to the right by one character, where directories are present on that row, in the previous columns. It seems that the width of the '/' at the end of the directory name is not accounted for, so the next column in the grid is 'pushed' one character along? (just a guess - but it only happens with directories and that slash is the only difference in their appearance, compared to files) Probably better explained with a screenshot:
![image](https://github.com/eza-community/eza/assets/132128962/9e529d44-2e4a-423f-afb5-6562897e54a2)

Hope this helps, thanks for sharing a nice tool :)

**Comment by PThorpe92** [comment] 2024-02-17 21:59
I believe the issue is the `classify=auto`, which would make this a duplicate of #845, which thankfully a fix for was just merged today :D  Expect this to be fixed at the next release :+1:

**Closed by PThorpe92** 2024-02-17 21:59 UTC
Labels: errors

**Comment by pallaswept** [comment] 2024-03-11 00:20
> I believe the issue is the `classify=auto`, which would make this a duplicate of #845, which thankfully a fix for was just merged today :D Expect this to be fixed at the next release 👍

Ahh right you are. It is fixed for me now (running 0.18.6). Thank you very much!
Sorry for filing a dupe, I didn't catch that one in my searches. Also apologies for the slow reply, I didn't get a notification for this :shrug:
