### ISSUE TITLE
bug: latest release `0.18.18` doesn't contain build assets

### ISSUE THREAD

**Issue by alessio-perugini** [eza-community/eza#1026] opened 2024-06-17 06:30 UTC
The latest release [v0.18.18](https://github.com/eza-community/eza/releases/tag/v0.18.18) doesn't contain the usual build assets for the OS's.
In previous releases, there were prebuilt binaries for all OSs and architecture.
Was this intentional?

**Comment by daviessm** [comment] 2024-06-17 07:07
Duplicate of #1023

**Closed by daviessm** 2024-06-17 07:07 UTC
Labels: errors
