### ISSUE TITLE
bug: listing symbolic link to unmounted network drive gives error

### ISSUE THREAD

**Issue by jonas-frey** [eza-community/eza#289] opened 2023-09-13 00:31 UTC
eza version: v0.11.1
OS: ubuntu 22.04 on intel

doing eza in a directory with a symbolic link to an unmounted network drive gives an error message. expected behavior (and exa behavior) is listing the link in red, to indicate that it's pointing nowhere. 

see the following screenshot:

![Screenshot_20230912_203023](https://github.com/eza-community/eza/assets/31709069/89942bff-eaf5-40c9-9b2e-37f45d2826c7)

**Comment by PThorpe92** [comment] 2023-09-13 00:35
https://github.com/eza-community/eza/pull/262 should be merged very soon and should clear this up :+1: 

Thank you for reporting it, closing issue as duplicate of #255

**Closed by PThorpe92** 2023-09-13 00:35 UTC
Labels: errors
