### ISSUE TITLE
bug: man pages and completion is not in archives

### ISSUE THREAD

**Issue by hoshsadiq** [eza-community/eza#500] opened 2023-10-08 20:51 UTC
Previously, exa included the shell completion scripts and the man pages in the archive. This doesn't seem to happen any more. Can this please be added again?

**Comment by gierens** [comment] 2023-10-08 21:07
Which archives do you mean? The assets on the release page?

**Comment by hoshsadiq** [comment] 2023-10-08 21:08
Yes correct. Sorry, I should have mentioned :)

**Comment by cafkafk** [comment] 2023-10-09 04:31
duplicate of #357, will do this soon, was blocked by #482, probably next release

**Closed by cafkafk** 2023-10-09 04:31 UTC
Labels: errors
